[package]
name = "test-kernel"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
edition = "2018"

[dependencies]
x86_64 = { version = "0.14.7", default-features = false, features = ["instructions", "inline_asm"] }
